export const initialData = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    clientEmail: "john@example.com",
    restaurantName: "The Harbor Kitchen",
    restaurantCuisine: "Seafood",
    status: "Active",
    healthScore: 92,
    franchise: "KFC",
    balance: "$1,200",
    nextMeeting: "2023-08-15",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    clientEmail: "jane@example.com",
    restaurantName: "Sunset Grill",
    restaurantCuisine: "American",
    status: "On Hold",
    healthScore: 48,
    franchise: "Burger King",
    balance: "$800",
    nextMeeting: "2023-08-20",
  },
  {
    id: 3,
    firstName: "Marcus",
    lastName: "Williams",
    clientEmail: "marcus@example.com",
    restaurantName: "The Rustic Table",
    restaurantCuisine: "Italian",
    status: "At Risk",
    healthScore: 55,
    franchise: "Subway",
    balance: "$2,400",
    nextMeeting: "2023-08-18",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    firstName: "Ana",
    lastName: "Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    firstName: "Ana",
    lastName: "Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    firstName: "Ana",
    lastName: "Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    firstName: "Ana",
    lastName: "Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    firstName: "Ana",
    lastName: "Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    firstName: "Ana",
    lastName: "Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    firstName: "Priya",
    lastName: "Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    firstName: "Ana",
    lastName: "Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
];


export const cardData = [
  {
    label: "Total Clients",
    value: "8",
    valueColor: "#2563EB",
  },
  {
    label: "Total Messages",
    value: "2",
    valueColor: "#22C55E",
  },
  {
    label: "Total Leads",
    value: "7",
    valueColor: "#EF4444",
  },
  {
    label: "Converted Leads",
    value: "6",
    valueColor: "#F59E0B",
  },
];
