export const initialData = [
  {
    id: 1,
    ownerName: "John Doe",
    clientEmail: "john@example.com",
    restaurantName: "The Harbor Kitchen",
    restaurantCuisine: "Seafood",
    status: "Active",
    healthScore: 92,
    franchise: "KFC",
    balance: "$1,200",
    nextMeeting: "2023-08-15",
  },
  {
    id: 2,
    ownerName: "Jane Smith",
    clientEmail: "jane@example.com",
    restaurantName: "Sunset Grill",
    restaurantCuisine: "American",
    status: "On Hold",
    healthScore: 48,
    franchise: "Burger King",
    balance: "$800",
    nextMeeting: "2023-08-20",
  },
  {
    id: 3,
    ownerName: "Marcus Williams",
    clientEmail: "marcus@example.com",
    restaurantName: "The Rustic Table",
    restaurantCuisine: "Italian",
    status: "At Risk",
    healthScore: 55,
    franchise: "Subway",
    balance: "$2,400",
    nextMeeting: "2023-08-18",
  },
  {
    id: 4,
    ownerName: "Priya Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    ownerName: "Ana Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    ownerName: "Priya Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    ownerName: "Ana Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    ownerName: "Priya Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    ownerName: "Ana Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    ownerName: "Priya Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    ownerName: "Ana Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    ownerName: "Priya Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    ownerName: "Ana Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    ownerName: "Priya Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    ownerName: "Ana Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
  {
    id: 4,
    ownerName: "Priya Patel",
    clientEmail: "priya@example.com",
    restaurantName: "Spice Route",
    restaurantCuisine: "Indian",
    status: "Pending",
    healthScore: 71,
    franchise: "Domino's",
    balance: "$540",
    nextMeeting: "2023-08-22",
  },
  {
    id: 5,
    ownerName: "Ana Torres",
    clientEmail: "ana@example.com",
    restaurantName: "Coastal Bistro",
    restaurantCuisine: "Mediterranean",
    status: "Active",
    healthScore: 84,
    franchise: "KFC",
    balance: "$1,800",
    nextMeeting: "2023-08-25",
  },
];
