export const INITIAL_BRANCHES = [
  {
    id: "branch-01",
    name: "Austin Central Branch",
    franchise: "BrightSmile Dental",
    city: "Austin, TX",
    lat: 30.2672,
    lng: -97.7431,
    radiusKm: 5,
  },
  {
    id: "branch-02",
    name: "Austin North Branch",
    franchise: "BrightSmile Dental",
    city: "Austin, TX",
    lat: 30.3801,
    lng: -97.7289,
    radiusKm: 5,
  },
  {
    id: "branch-03",
    name: "Denver Downtown Studio",
    franchise: "UrbanFit Studios",
    city: "Denver, CO",
    lat: 39.7392,
    lng: -104.9903,
    radiusKm: 8,
  },
  {
    id: "branch-04",
    name: "Seattle Harbor Cafe",
    franchise: "GreenLeaf Cafe",
    city: "Seattle, WA",
    lat: 47.6062,
    lng: -122.3321,
    radiusKm: 4,
  },
  {
    id: "branch-05",
    name: "Phoenix Airport Hub",
    franchise: "QuickLube Auto",
    city: "Phoenix, AZ",
    lat: 33.4484,
    lng: -112.074,
    radiusKm: 6,
  },
  {
    id: "branch-06",
    name: "Miami South Beach Clinic",
    franchise: "BrightSmile Dental",
    city: "Miami, FL",
    lat: 25.7617,
    lng: -80.1918,
    radiusKm: 6,
  },
];
