export const initialDocuments = [
  {
    id: 1,
    document: "California State FDD 2025.pdf",
    version: "3.2",
    brand: "Burger Hub",
    country: "United States",
    state: "California",
    status: "Approved",
  },
  {
    id: 2,
    document: "New York State FDD 2025.pdf",
    version: "4.0",
    brand: "Burger Hub",
    country: "United States",
    state: "New York",
    status: "Approved",
  },
  {
    id: 3,
    document: "General US Federal FDD 2025.pdf",
    version: "5.0",
    brand: "Burger Hub",
    country: "United States",
    state: "Texas",
    status: "Approved",
  },
  {
    id: 4,
    document: "Pizza Corner Disclosure.pdf",
    version: "1.0",
    brand: "Pizza Corner",
    country: "USA",
    state: "Ontario",
    status: "Pending",
  },
  {
    id: 5,
    document: "Sushi Place FDD.pdf",
    version: "1.2",
    brand: "Sushi Place",
    country: "United Kingdom",
    state: "London",
    status: "Draft",
  },
];
