export const initialModerators = [
  {
    id: 1,
    firstName: "Sarah",
    lastName: "Chen",
    fullName: "Sarah Chen",
    email: "sarah.chen@example.com",
    phone: "(415) 555-0142",
    city: "San Francisco",
    state: "California",
    country: "United States",
    status: "Active",
    role: "Moderator",
    joined: "Added 2 days ago",
  },
  {
    id: 2,
    firstName: "Marcus",
    lastName: "Lee",
    fullName: "Marcus Lee",
    email: "marcus.lee@example.com",
    phone: "(312) 555-0187",
    city: "Chicago",
    state: "Illinois",
    country: "United States",
    status: "Active",
    role: "Moderator",
    joined: "Added 1 week ago",
  },
  {
    id: 3,
    firstName: "Priya",
    lastName: "Sharma",
    fullName: "Priya Sharma",
    email: "priya.sharma@example.com",
    phone: "(512) 555-0119",
    city: "Austin",
    state: "Texas",
    country: "United States",
    status: "Inactive",
    role: "Moderator",
    joined: "Added 3 days ago",
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Okafor",
    fullName: "David Okafor",
    email: "david.okafor@example.com",
    phone: "(305) 555-0163",
    city: "Miami",
    state: "Florida",
    country: "United States",
    status: "Active",
    role: "Moderator",
    joined: "Added 1 month ago",
  },
];
