export const initialApplicants = [
  {
    id: "FR-001",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@mail.com",
    avatar: "",
    franchise: "BrightSmile Dental",
    territory: "Austin, TX",
    stage: "Document Collection",
    score: 82,
    financial: "$250,000",
    submitted: "12 Aug 2026",
  },
  {
    id: "FR-002",
    name: "David Chen",
    email: "d.chen@mail.com",
    avatar: "",
    franchise: "UrbanFit Studios",
    territory: "Denver, CO",
    stage: "Committee Review",
    score: 64,
    financial: "$180,000",
    submitted: "10 Aug 2026",
  },
  {
    id: "FR-003",
    name: "Priya Nair",
    email: "priya.nair@mail.com",
    avatar: "",
    franchise: "GreenLeaf Cafe",
    territory: "Seattle, WA",
    stage: "Conditionally Approved",
    score: 91,
    financial: "$320,000",
    submitted: "08 Aug 2026",
  },
  {
    id: "FR-004",
    name: "Marcus Reid",
    email: "m.reid@mail.com",
    avatar: "",
    franchise: "QuickLube Auto",
    territory: "Phoenix, AZ",
    stage: "Denied",
    score: 38,
    financial: "$95,000",
    submitted: "05 Aug 2026",
  },
  {
    id: "FR-005",
    name: "Elena Duarte",
    email: "elena.duarte@mail.com",
    avatar: "",
    franchise: "BrightSmile Dental",
    territory: "Miami, FL",
    stage: "Approved",
    score: 88,
    financial: "$275,000",
    submitted: "02 Aug 2026",
  },
];
