export const EMPTY_TICKET = {
  subject: "",
  category: "",
  priority: "",
  description: "",
  attachment: null,
};

export const initialTickets = [
  {
    id: 1,
    ticketId: "#TKT-1001",
    subject: "Unable to upload FDD document",
    category: "Documents",
    priority: "Critical",
    status: "in_progress",
    description:
      "Uploading the 2026 FDD fails at 80% with a network error. Tried Chrome and Safari, same result on a 12 MB PDF.",
    receivedOn: "12 Aug 2026",
    lastUpdated: "14 Aug 2026",
  },
  {
    id: 2,
    ticketId: "#TKT-1007",
    subject: "Add a second manager to our account",
    category: "Account",
    priority: "Medium",
    status: "in_progress",
    description: "We hired a new general manager and would like a moderator login created for her.",
    receivedOn: "09 Aug 2026",
    lastUpdated: "11 Aug 2026",
  },
  {
    id: 3,
    ticketId: "#TKT-1003",
    subject: "Payment receipt not generated",
    category: "Billing",
    priority: "Medium",
    status: "resolved",
    description: "The August royalty payment went through but no receipt was generated in the billing section.",
    receivedOn: "05 Aug 2026",
    lastUpdated: "08 Aug 2026",
  },
  {
    id: 4,
    ticketId: "#TKT-1004",
    subject: "Request to update restaurant brand name",
    category: "General",
    priority: "Low",
    status: "closed",
    description: "We have rebranded and would like the dashboard to show the new trading name.",
    receivedOn: "01 Aug 2026",
    lastUpdated: "03 Aug 2026",
  },
];
