export const initialApplicants = [
  {
    id: "FR-001",
    name: "Renee Sato",
    company: "Sato New Ventures",
    territory: "Boise, ID",
    stage: "Document Collection",
    score: 47.3,
    submitted: "06/20/2026",
    weighted: { financial: 8.0, experience: 10.0, legal: 16.0, market: 13.3 },
    categories: { financial: 1.1, experience: 2.5, legal: 4.0, market: 2.7 },
    financialProfile: [
      { label: "Liquid Capital", value: "$90K", hint: "Below min.", ok: false },
      { label: "Net Worth", value: "$210K", hint: "Below min.", ok: false },
      { label: "Credit Score", value: "690", hint: "Meets min.", ok: true },
    ],
    experience: [
      { label: "Years Mgmt", value: "4" },
      { label: "Food/Restaurant", value: "No", ok: false },
      { label: "Multi-Unit Op.", value: "Yes", ok: true },
    ],
    legal: [
      { label: "Pending Litigation", value: "NO", ok: true },
      { label: "Criminal Background", value: "NO", ok: true },
      { label: "Non-Compete Conflict", value: "YES", ok: false },
    ],
    market: [
      { label: "Territory", value: "Available", ok: true },
      { label: "Competition", value: "Medium" },
      { label: "Market Score", value: "2.7" },
    ],
  },
  {
    id: "FR-003",
    name: "Marcus Webb",
    company: "Webb Ventures",
    territory: "Reno, NV",
    stage: "Under Review",
    score: 36.0,
    submitted: "04/02/2026",
    weighted: { financial: 0.0, experience: 2.7, legal: 13.3, market: 20.0 },
    categories: { financial: 0.0, experience: 0.7, legal: 3.3, market: 4.0 },
    financialProfile: [
      { label: "Liquid Capital", value: "$40K", hint: "Below min.", ok: false },
      { label: "Net Worth", value: "$120K", hint: "Below min.", ok: false },
      { label: "Credit Score", value: "640", hint: "Below min.", ok: false },
    ],
    experience: [
      { label: "Years Mgmt", value: "1" },
      { label: "Food/Restaurant", value: "No", ok: false },
      { label: "Multi-Unit Op.", value: "No", ok: false },
    ],
    legal: [
      { label: "Pending Litigation", value: "NO", ok: true },
      { label: "Criminal Background", value: "NO", ok: true },
      { label: "Non-Compete Conflict", value: "NO", ok: true },
    ],
    market: [
      { label: "Territory", value: "Available", ok: true },
      { label: "Competition", value: "High", ok: false },
      { label: "Market Score", value: "2.7" },
    ],
  },
  {
    id: "FR-002",
    name: "Angela Brooks",
    company: "Brooks Holdings",
    territory: "Charlotte, NC",
    stage: "Conditionally Approved",
    score: 69.3,
    submitted: "02/10/2026",
    weighted: { financial: 24.5, experience: 14.0, legal: 16.0, market: 14.8 },
    categories: { financial: 3.5, experience: 3.5, legal: 4.0, market: 3.0 },
    financialProfile: [
      { label: "Liquid Capital", value: "$180K", hint: "Meets min.", ok: true },
      { label: "Net Worth", value: "$420K", hint: "Meets min.", ok: true },
      { label: "Credit Score", value: "710", hint: "Meets min.", ok: true },
    ],
    experience: [
      { label: "Years Mgmt", value: "8" },
      { label: "Food/Restaurant", value: "Yes", ok: true },
      { label: "Multi-Unit Op.", value: "No", ok: false },
    ],
    legal: [
      { label: "Pending Litigation", value: "NO", ok: true },
      { label: "Criminal Background", value: "NO", ok: true },
      { label: "Non-Compete Conflict", value: "NO", ok: true },
    ],
    market: [
      { label: "Territory", value: "Available", ok: true },
      { label: "Competition", value: "Medium" },
      { label: "Market Score", value: "3.0" },
    ],
  },
];
