// 14 states need their own FDD
export const GENERAL_FDD_STATE = "General";

export const US_STATES = [
  { name: "Alabama", code: "AL", isRegistrationState: false },
  { name: "Alaska", code: "AK", isRegistrationState: false },
  { name: "Arizona", code: "AZ", isRegistrationState: false },
  { name: "Arkansas", code: "AR", isRegistrationState: false },
  { name: "California", code: "CA", isRegistrationState: true },
  { name: "Colorado", code: "CO", isRegistrationState: false },
  { name: "Connecticut", code: "CT", isRegistrationState: false },
  { name: "Delaware", code: "DE", isRegistrationState: false },
  { name: "Florida", code: "FL", isRegistrationState: false },
  { name: "Georgia", code: "GA", isRegistrationState: false },
  { name: "Hawaii", code: "HI", isRegistrationState: true },
  { name: "Idaho", code: "ID", isRegistrationState: false },
  { name: "Illinois", code: "IL", isRegistrationState: true },
  { name: "Indiana", code: "IN", isRegistrationState: true },
  { name: "Iowa", code: "IA", isRegistrationState: false },
  { name: "Kansas", code: "KS", isRegistrationState: false },
  { name: "Kentucky", code: "KY", isRegistrationState: false },
  { name: "Louisiana", code: "LA", isRegistrationState: false },
  { name: "Maine", code: "ME", isRegistrationState: false },
  { name: "Maryland", code: "MD", isRegistrationState: true },
  { name: "Massachusetts", code: "MA", isRegistrationState: false },
  { name: "Michigan", code: "MI", isRegistrationState: true },
  { name: "Minnesota", code: "MN", isRegistrationState: true },
  { name: "Mississippi", code: "MS", isRegistrationState: false },
  { name: "Missouri", code: "MO", isRegistrationState: false },
  { name: "Montana", code: "MT", isRegistrationState: false },
  { name: "Nebraska", code: "NE", isRegistrationState: false },
  { name: "Nevada", code: "NV", isRegistrationState: false },
  { name: "New Hampshire", code: "NH", isRegistrationState: false },
  { name: "New Jersey", code: "NJ", isRegistrationState: false },
  { name: "New Mexico", code: "NM", isRegistrationState: false },
  { name: "New York", code: "NY", isRegistrationState: true },
  { name: "North Carolina", code: "NC", isRegistrationState: false },
  { name: "North Dakota", code: "ND", isRegistrationState: true },
  { name: "Ohio", code: "OH", isRegistrationState: false },
  { name: "Oklahoma", code: "OK", isRegistrationState: false },
  { name: "Oregon", code: "OR", isRegistrationState: false },
  { name: "Pennsylvania", code: "PA", isRegistrationState: false },
  { name: "Rhode Island", code: "RI", isRegistrationState: true },
  { name: "South Carolina", code: "SC", isRegistrationState: false },
  { name: "South Dakota", code: "SD", isRegistrationState: true },
  { name: "Tennessee", code: "TN", isRegistrationState: false },
  { name: "Texas", code: "TX", isRegistrationState: false },
  { name: "Utah", code: "UT", isRegistrationState: false },
  { name: "Vermont", code: "VT", isRegistrationState: false },
  { name: "Virginia", code: "VA", isRegistrationState: true },
  { name: "Washington", code: "WA", isRegistrationState: true },
  { name: "West Virginia", code: "WV", isRegistrationState: false },
  { name: "Wisconsin", code: "WI", isRegistrationState: true },
  { name: "Wyoming", code: "WY", isRegistrationState: false },
];

// general, then the registration states
export const FDD_STATE_OPTIONS = [
  GENERAL_FDD_STATE,
  ...US_STATES.filter((state) => state.isRegistrationState).map((state) => state.name),
];
